# Generated by Django 3.2 on 2023-06-21 20:25

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reworkeduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[users.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='reworkeduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[users.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='reworkeduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.validators.validate_username]),
        ),
    ]
