# Generated by Django 3.2 on 2023-06-22 13:11

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_reworkeduser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reworkeduser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='reworkeduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator, users.validators.validate_username]),
        ),
    ]
